/* Vocabulario de inglés — parte 2. Formato: [inglés, español, emoji o "", categoría, nivel 1-3] */
(window.INGLES = window.INGLES || { vocab: [], gramatica: [], frases: [] }).vocab.push(
  // ---------- Verbos ----------
  ["run", "correr", "🏃", "Verbos", 1],
  ["swim", "nadar", "🏊", "Verbos", 1],
  ["jump", "saltar", "", "Verbos", 1],
  ["eat", "comer", "", "Verbos", 1],
  ["drink", "beber", "", "Verbos", 1],
  ["sleep", "dormir", "😴", "Verbos", 1],
  ["read", "leer", "📖", "Verbos", 1],
  ["write", "escribir", "✍️", "Verbos", 1],
  ["sing", "cantar", "🎤", "Verbos", 1],
  ["dance", "bailar", "💃", "Verbos", 1],
  ["play", "jugar", "", "Verbos", 1],
  ["walk", "caminar", "🚶", "Verbos", 1],
  ["climb", "escalar", "🧗", "Verbos", 2],
  ["cook", "cocinar", "", "Verbos", 2],
  ["draw", "dibujar", "✏️", "Verbos", 2],
  ["paint", "pintar", "🎨", "Verbos", 2],
  ["listen", "escuchar", "👂", "Verbos", 2],
  ["laugh", "reír", "😂", "Verbos", 2],
  ["cry", "llorar", "😢", "Verbos", 2],
  ["build", "construir", "", "Verbos", 2],
  ["catch", "atrapar", "", "Verbos", 2],
  ["throw", "lanzar", "", "Verbos", 2],
  ["fly", "volar", "", "Verbos", 2],
  ["forget", "olvidar", "", "Verbos", 2],
  ["remember", "recordar", "", "Verbos", 2],
  ["choose", "elegir", "", "Verbos", 2],
  ["borrow", "pedir prestado", "", "Verbos", 2],
  ["whisper", "susurrar", "🤫", "Verbos", 3],
  ["explore", "explorar", "", "Verbos", 3],
  ["discover", "descubrir", "", "Verbos", 3],
  ["imagine", "imaginar", "", "Verbos", 3],
  ["achieve", "lograr", "", "Verbos", 3],
  ["breathe", "respirar", "", "Verbos", 3],
  ["pretend", "fingir", "", "Verbos", 3],
  ["improve", "mejorar", "", "Verbos", 3],
  ["suggest", "sugerir", "", "Verbos", 3],
  ["gather", "reunir", "", "Verbos", 3],

  // ---------- Verbos en pasado ----------
  ["played", "jugó (play)", "", "Verbos en pasado", 1],
  ["jumped", "saltó (jump)", "", "Verbos en pasado", 1],
  ["walked", "caminó (walk)", "", "Verbos en pasado", 1],
  ["went", "fue / se fue (go)", "", "Verbos en pasado", 1],
  ["ate", "comió (eat)", "", "Verbos en pasado", 1],
  ["saw", "vio (see)", "", "Verbos en pasado", 1],
  ["had", "tuvo (have)", "", "Verbos en pasado", 1],
  ["was", "era / estaba (be)", "", "Verbos en pasado", 1],
  ["ran", "corrió (run)", "", "Verbos en pasado", 1],
  ["made", "hizo (make)", "", "Verbos en pasado", 1],
  ["drank", "bebió (drink)", "", "Verbos en pasado", 2],
  ["swam", "nadó (swim)", "", "Verbos en pasado", 2],
  ["sang", "cantó (sing)", "", "Verbos en pasado", 2],
  ["wrote", "escribió (write)", "", "Verbos en pasado", 2],
  ["came", "vino (come)", "", "Verbos en pasado", 2],
  ["took", "tomó (take)", "", "Verbos en pasado", 2],
  ["gave", "dio (give)", "", "Verbos en pasado", 2],
  ["found", "encontró (find)", "", "Verbos en pasado", 2],
  ["bought", "compró (buy)", "", "Verbos en pasado", 2],
  ["slept", "durmió (sleep)", "", "Verbos en pasado", 2],
  ["told", "contó (tell)", "", "Verbos en pasado", 2],
  ["said", "dijo (say)", "", "Verbos en pasado", 2],
  ["flew", "voló (fly)", "", "Verbos en pasado", 2],
  ["began", "comenzó (begin)", "", "Verbos en pasado", 2],
  ["won", "ganó (win)", "", "Verbos en pasado", 2],
  ["lost", "perdió (lose)", "", "Verbos en pasado", 2],
  ["caught", "atrapó (catch)", "", "Verbos en pasado", 2],
  ["studied", "estudió (study)", "", "Verbos en pasado", 2],
  ["thought", "pensó (think)", "", "Verbos en pasado", 3],
  ["brought", "trajo (bring)", "", "Verbos en pasado", 3],
  ["taught", "enseñó (teach)", "", "Verbos en pasado", 3],
  ["fought", "peleó (fight)", "", "Verbos en pasado", 3],
  ["chose", "eligió (choose)", "", "Verbos en pasado", 3],
  ["forgot", "olvidó (forget)", "", "Verbos en pasado", 3],
  ["understood", "entendió (understand)", "", "Verbos en pasado", 3],
  ["hid", "se escondió (hide)", "", "Verbos en pasado", 3],
  ["froze", "se congeló (freeze)", "", "Verbos en pasado", 3],
  ["dug", "cavó (dig)", "", "Verbos en pasado", 3],
  ["knelt", "se arrodilló (kneel)", "", "Verbos en pasado", 3],
  ["bit", "mordió (bite)", "", "Verbos en pasado", 3],

  // ---------- Adjetivos ----------
  ["big", "grande", "", "Adjetivos", 1],
  ["small", "pequeño", "", "Adjetivos", 1],
  ["hot", "caliente", "🔥", "Adjetivos", 1],
  ["cold", "frío", "🥶", "Adjetivos", 1],
  ["fast", "rápido", "", "Adjetivos", 1],
  ["slow", "lento", "🐢", "Adjetivos", 1],
  ["tall", "alto", "", "Adjetivos", 1],
  ["new", "nuevo", "", "Adjetivos", 1],
  ["old", "viejo", "", "Adjetivos", 1],
  ["beautiful", "hermoso", "", "Adjetivos", 1],
  ["brave", "valiente", "", "Adjetivos", 2],
  ["strong", "fuerte", "💪", "Adjetivos", 2],
  ["weak", "débil", "", "Adjetivos", 2],
  ["heavy", "pesado", "", "Adjetivos", 2],
  ["empty", "vacío", "", "Adjetivos", 2],
  ["full", "lleno", "", "Adjetivos", 2],
  ["dark", "oscuro", "", "Adjetivos", 2],
  ["bright", "brillante", "", "Adjetivos", 2],
  ["soft", "suave", "", "Adjetivos", 2],
  ["hard", "duro", "", "Adjetivos", 2],
  ["dirty", "sucio", "", "Adjetivos", 2],
  ["clean", "limpio", "", "Adjetivos", 2],
  ["wet", "mojado", "", "Adjetivos", 2],
  ["dry", "seco", "", "Adjetivos", 2],
  ["loud", "ruidoso", "", "Adjetivos", 2],
  ["quiet", "silencioso", "", "Adjetivos", 2],
  ["funny", "chistoso", "", "Adjetivos", 2],
  ["dangerous", "peligroso", "", "Adjetivos", 2],
  ["ancient", "antiguo", "", "Adjetivos", 3],
  ["enormous", "enorme", "", "Adjetivos", 3],
  ["tiny", "diminuto", "", "Adjetivos", 3],
  ["fierce", "feroz", "", "Adjetivos", 3],
  ["delicate", "delicado", "", "Adjetivos", 3],
  ["clever", "astuto", "", "Adjetivos", 3],
  ["curious", "curioso", "", "Adjetivos", 3],
  ["mysterious", "misterioso", "", "Adjetivos", 3],
  ["generous", "generoso", "", "Adjetivos", 3],
  ["honest", "honesto", "", "Adjetivos", 3],
  ["polite", "educado", "", "Adjetivos", 3],
  ["valuable", "valioso", "", "Adjetivos", 3],

  // ---------- Emociones ----------
  ["happy", "feliz", "😊", "Emociones", 1],
  ["sad", "triste", "😢", "Emociones", 1],
  ["angry", "enojado", "😠", "Emociones", 1],
  ["scared", "asustado", "😨", "Emociones", 1],
  ["tired", "cansado", "😫", "Emociones", 1],
  ["love", "amor", "❤️", "Emociones", 1],
  ["hungry", "con hambre", "", "Emociones", 1],
  ["sleepy", "con sueño", "😪", "Emociones", 1],
  ["bored", "aburrido", "🥱", "Emociones", 2],
  ["surprised", "sorprendido", "😲", "Emociones", 2],
  ["worried", "preocupado", "😟", "Emociones", 2],
  ["excited", "emocionado", "🤩", "Emociones", 2],
  ["nervous", "nervioso", "😬", "Emociones", 2],
  ["proud", "orgulloso", "", "Emociones", 2],
  ["shy", "tímido", "", "Emociones", 2],
  ["lonely", "solitario", "", "Emociones", 2],
  ["calm", "tranquilo", "😌", "Emociones", 2],
  ["confused", "confundido", "😕", "Emociones", 2],
  ["jealous", "celoso", "", "Emociones", 2],
  ["embarrassed", "avergonzado", "😳", "Emociones", 2],
  ["fear", "miedo", "", "Emociones", 2],
  ["joy", "alegría", "", "Emociones", 2],
  ["furious", "furioso", "😡", "Emociones", 3],
  ["grateful", "agradecido", "🙏", "Emociones", 3],
  ["disappointed", "decepcionado", "😞", "Emociones", 3],
  ["frustrated", "frustrado", "😤", "Emociones", 3],
  ["anxious", "ansioso", "", "Emociones", 3],
  ["relieved", "aliviado", "😮‍💨", "Emociones", 3],
  ["delighted", "encantado", "", "Emociones", 3],
  ["hopeful", "esperanzado", "", "Emociones", 3],
  ["confident", "seguro de sí mismo", "", "Emociones", 3],
  ["amazed", "asombrado", "", "Emociones", 3],
  ["terrified", "aterrorizado", "😱", "Emociones", 3],
  ["nostalgic", "nostálgico", "", "Emociones", 3],

  // ---------- Profesiones ----------
  ["teacher", "profesor", "🧑‍🏫", "Profesiones", 1],
  ["doctor", "médico", "🧑‍⚕️", "Profesiones", 1],
  ["farmer", "agricultor", "🧑‍🌾", "Profesiones", 1],
  ["chef", "chef", "🧑‍🍳", "Profesiones", 1],
  ["police officer", "policía", "👮", "Profesiones", 1],
  ["firefighter", "bombero", "🧑‍🚒", "Profesiones", 1],
  ["nurse", "enfermero", "", "Profesiones", 1],
  ["singer", "cantante", "🧑‍🎤", "Profesiones", 1],
  ["dentist", "dentista", "", "Profesiones", 1],
  ["vet", "veterinario", "", "Profesiones", 1],
  ["pilot", "piloto", "🧑‍✈️", "Profesiones", 2],
  ["astronaut", "astronauta", "🧑‍🚀", "Profesiones", 2],
  ["artist", "artista", "🧑‍🎨", "Profesiones", 2],
  ["baker", "panadero", "", "Profesiones", 2],
  ["mechanic", "mecánico", "🧑‍🔧", "Profesiones", 2],
  ["scientist", "científico", "🧑‍🔬", "Profesiones", 2],
  ["writer", "escritor", "", "Profesiones", 2],
  ["driver", "conductor", "", "Profesiones", 2],
  ["waiter", "garzón", "", "Profesiones", 2],
  ["dancer", "bailarín", "", "Profesiones", 2],
  ["fisherman", "pescador", "", "Profesiones", 2],
  ["gardener", "jardinero", "", "Profesiones", 2],
  ["carpenter", "carpintero", "", "Profesiones", 2],
  ["hairdresser", "peluquero", "💇", "Profesiones", 2],
  ["librarian", "bibliotecario", "", "Profesiones", 2],
  ["lawyer", "abogado", "", "Profesiones", 2],
  ["photographer", "fotógrafo", "📷", "Profesiones", 2],
  ["architect", "arquitecto", "", "Profesiones", 3],
  ["engineer", "ingeniero", "", "Profesiones", 3],
  ["journalist", "periodista", "", "Profesiones", 3],
  ["surgeon", "cirujano", "", "Profesiones", 3],
  ["plumber", "gasfíter", "", "Profesiones", 3],
  ["electrician", "electricista", "", "Profesiones", 3],
  ["archaeologist", "arqueólogo", "", "Profesiones", 3],
  ["astronomer", "astrónomo", "🔭", "Profesiones", 3],
  ["detective", "detective", "🕵️", "Profesiones", 3],
  ["inventor", "inventor", "", "Profesiones", 3],
  ["programmer", "programador", "🧑‍💻", "Profesiones", 3],
  ["translator", "traductor", "", "Profesiones", 3],

  // ---------- Deportes y pasatiempos ----------
  ["soccer", "fútbol", "⚽", "Deportes y pasatiempos", 1],
  ["basketball", "básquetbol", "🏀", "Deportes y pasatiempos", 1],
  ["tennis", "tenis", "🎾", "Deportes y pasatiempos", 1],
  ["swimming", "natación", "🏊", "Deportes y pasatiempos", 1],
  ["ball", "pelota", "", "Deportes y pasatiempos", 1],
  ["bike", "bicicleta", "🚲", "Deportes y pasatiempos", 1],
  ["game", "juego", "🎮", "Deportes y pasatiempos", 1],
  ["kite", "volantín", "🪁", "Deportes y pasatiempos", 1],
  ["toy", "juguete", "🧸", "Deportes y pasatiempos", 1],
  ["music", "música", "🎵", "Deportes y pasatiempos", 1],
  ["volleyball", "vóleibol", "🏐", "Deportes y pasatiempos", 2],
  ["baseball", "béisbol", "⚾", "Deportes y pasatiempos", 2],
  ["skating", "patinaje", "⛸️", "Deportes y pasatiempos", 2],
  ["skateboard", "patineta", "🛹", "Deportes y pasatiempos", 2],
  ["cycling", "ciclismo", "🚴", "Deportes y pasatiempos", 2],
  ["surfing", "surf", "🏄", "Deportes y pasatiempos", 2],
  ["skiing", "esquí", "⛷️", "Deportes y pasatiempos", 2],
  ["boxing", "boxeo", "🥊", "Deportes y pasatiempos", 2],
  ["chess", "ajedrez", "♟️", "Deportes y pasatiempos", 2],
  ["puzzle", "rompecabezas", "🧩", "Deportes y pasatiempos", 2],
  ["hobby", "pasatiempo", "", "Deportes y pasatiempos", 2],
  ["team", "equipo", "", "Deportes y pasatiempos", 2],
  ["karate", "karate", "🥋", "Deportes y pasatiempos", 2],
  ["camping", "campamento", "⛺", "Deportes y pasatiempos", 2],
  ["hiking", "senderismo", "🥾", "Deportes y pasatiempos", 2],
  ["gymnastics", "gimnasia", "🤸", "Deportes y pasatiempos", 3],
  ["athletics", "atletismo", "", "Deportes y pasatiempos", 3],
  ["archery", "tiro con arco", "🏹", "Deportes y pasatiempos", 3],
  ["fencing", "esgrima", "🤺", "Deportes y pasatiempos", 3],
  ["rowing", "remo", "🚣", "Deportes y pasatiempos", 3],
  ["diving", "buceo", "🤿", "Deportes y pasatiempos", 3],
  ["climbing", "escalada", "🧗", "Deportes y pasatiempos", 3],
  ["referee", "árbitro", "", "Deportes y pasatiempos", 3],
  ["tournament", "torneo", "", "Deportes y pasatiempos", 3],
  ["trophy", "trofeo", "🏆", "Deportes y pasatiempos", 3],
  ["medal", "medalla", "🏅", "Deportes y pasatiempos", 3],
  ["champion", "campeón", "", "Deportes y pasatiempos", 3],
  ["horse riding", "equitación", "🏇", "Deportes y pasatiempos", 3],
  ["photography", "fotografía", "", "Deportes y pasatiempos", 3],
  ["knitting", "tejido", "🧶", "Deportes y pasatiempos", 3],

  // ---------- Tiempo y calendario ----------
  ["Monday", "lunes", "", "Tiempo y calendario", 1],
  ["Tuesday", "martes", "", "Tiempo y calendario", 1],
  ["Wednesday", "miércoles", "", "Tiempo y calendario", 1],
  ["Thursday", "jueves", "", "Tiempo y calendario", 1],
  ["Friday", "viernes", "", "Tiempo y calendario", 1],
  ["Saturday", "sábado", "", "Tiempo y calendario", 1],
  ["Sunday", "domingo", "", "Tiempo y calendario", 1],
  ["today", "hoy", "", "Tiempo y calendario", 1],
  ["tomorrow", "mañana", "", "Tiempo y calendario", 1],
  ["night", "noche", "🌙", "Tiempo y calendario", 1],
  ["January", "enero", "", "Tiempo y calendario", 2],
  ["February", "febrero", "", "Tiempo y calendario", 2],
  ["March", "marzo", "", "Tiempo y calendario", 2],
  ["April", "abril", "", "Tiempo y calendario", 2],
  ["May", "mayo", "", "Tiempo y calendario", 2],
  ["June", "junio", "", "Tiempo y calendario", 2],
  ["July", "julio", "", "Tiempo y calendario", 2],
  ["August", "agosto", "", "Tiempo y calendario", 2],
  ["September", "septiembre", "", "Tiempo y calendario", 2],
  ["October", "octubre", "", "Tiempo y calendario", 2],
  ["November", "noviembre", "", "Tiempo y calendario", 2],
  ["December", "diciembre", "", "Tiempo y calendario", 2],
  ["spring", "primavera", "🌸", "Tiempo y calendario", 2],
  ["summer", "verano", "☀️", "Tiempo y calendario", 2],
  ["autumn", "otoño", "🍂", "Tiempo y calendario", 2],
  ["winter", "invierno", "❄️", "Tiempo y calendario", 2],
  ["yesterday", "ayer", "", "Tiempo y calendario", 2],
  ["month", "mes", "", "Tiempo y calendario", 2],
  ["year", "año", "", "Tiempo y calendario", 2],
  ["hour", "hora", "", "Tiempo y calendario", 2],
  ["weekend", "fin de semana", "", "Tiempo y calendario", 2],
  ["calendar", "calendario", "📅", "Tiempo y calendario", 2],
  ["afternoon", "tarde", "", "Tiempo y calendario", 2],
  ["fortnight", "quincena", "", "Tiempo y calendario", 3],
  ["midnight", "medianoche", "", "Tiempo y calendario", 3],
  ["century", "siglo", "", "Tiempo y calendario", 3],
  ["decade", "década", "", "Tiempo y calendario", 3],
  ["dawn", "amanecer", "🌅", "Tiempo y calendario", 3],
  ["noon", "mediodía", "", "Tiempo y calendario", 3],
  ["schedule", "horario", "", "Tiempo y calendario", 3],
  ["leap year", "año bisiesto", "", "Tiempo y calendario", 3],
  ["sunset", "atardecer", "🌇", "Tiempo y calendario", 3],
  ["millennium", "milenio", "", "Tiempo y calendario", 3],

  // ---------- Números ----------
  ["eleven", "once", "", "Números", 1],
  ["twelve", "doce", "", "Números", 1],
  ["thirteen", "trece", "", "Números", 1],
  ["fifteen", "quince", "", "Números", 1],
  ["twenty", "veinte", "", "Números", 1],
  ["thirty", "treinta", "", "Números", 1],
  ["first", "primero", "🥇", "Números", 1],
  ["second", "segundo", "🥈", "Números", 1],
  ["third", "tercero", "🥉", "Números", 1],
  ["one hundred", "cien", "💯", "Números", 1],
  ["fourteen", "catorce", "", "Números", 2],
  ["sixteen", "dieciséis", "", "Números", 2],
  ["seventeen", "diecisiete", "", "Números", 2],
  ["eighteen", "dieciocho", "", "Números", 2],
  ["nineteen", "diecinueve", "", "Números", 2],
  ["forty", "cuarenta", "", "Números", 2],
  ["fifty", "cincuenta", "", "Números", 2],
  ["sixty", "sesenta", "", "Números", 2],
  ["seventy", "setenta", "", "Números", 2],
  ["eighty", "ochenta", "", "Números", 2],
  ["ninety", "noventa", "", "Números", 2],
  ["fourth", "cuarto", "", "Números", 2],
  ["fifth", "quinto", "", "Números", 2],
  ["twenty-one", "veintiuno", "", "Números", 2],
  ["thousand", "mil", "", "Números", 2],
  ["forty-seven", "cuarenta y siete", "", "Números", 3],
  ["ninety-nine", "noventa y nueve", "", "Números", 3],
  ["one hundred and five", "ciento cinco", "", "Números", 3],
  ["million", "millón", "", "Números", 3],
  ["twelfth", "duodécimo", "", "Números", 3],
  ["ninth", "noveno", "", "Números", 3],
  ["eighth", "octavo", "", "Números", 3],
  ["twentieth", "vigésimo", "", "Números", 3],
  ["hundredth", "centésimo", "", "Números", 3],
  ["forty-seventh", "cuadragésimo séptimo", "", "Números", 3],
  ["sixty-three", "sesenta y tres", "", "Números", 3],
  ["dozen", "docena", "", "Números", 3],

  // ---------- Magia y fantasía ----------
  ["magic", "magia", "✨", "Magia y fantasía", 1],
  ["wand", "varita", "🪄", "Magia y fantasía", 1],
  ["witch", "bruja", "🧙‍♀️", "Magia y fantasía", 1],
  ["dragon", "dragón", "🐉", "Magia y fantasía", 1],
  ["castle", "castillo", "🏰", "Magia y fantasía", 1],
  ["fairy", "hada", "🧚", "Magia y fantasía", 1],
  ["unicorn", "unicornio", "🦄", "Magia y fantasía", 1],
  ["ghost", "fantasma", "👻", "Magia y fantasía", 1],
  ["princess", "princesa", "👸", "Magia y fantasía", 1],
  ["prince", "príncipe", "🤴", "Magia y fantasía", 1],
  ["spell", "hechizo", "", "Magia y fantasía", 2],
  ["potion", "poción", "🧪", "Magia y fantasía", 2],
  ["broom", "escoba", "🧹", "Magia y fantasía", 2],
  ["wizard", "mago", "🧙", "Magia y fantasía", 2],
  ["mermaid", "sirena", "🧜‍♀️", "Magia y fantasía", 2],
  ["giant", "gigante", "", "Magia y fantasía", 2],
  ["treasure", "tesoro", "💎", "Magia y fantasía", 2],
  ["crown", "corona", "👑", "Magia y fantasía", 2],
  ["tower", "torre", "", "Magia y fantasía", 2],
  ["cauldron", "caldero", "", "Magia y fantasía", 2],
  ["elf", "elfo", "🧝", "Magia y fantasía", 2],
  ["genie", "genio", "🧞", "Magia y fantasía", 2],
  ["crystal ball", "bola de cristal", "🔮", "Magia y fantasía", 2],
  ["knight", "caballero", "", "Magia y fantasía", 2],
  ["dwarf", "enano", "", "Magia y fantasía", 2],
  ["enchantment", "encantamiento", "", "Magia y fantasía", 3],
  ["sorcerer", "hechicero", "", "Magia y fantasía", 3],
  ["phoenix", "fénix", "", "Magia y fantasía", 3],
  ["griffin", "grifo", "", "Magia y fantasía", 3],
  ["curse", "maldición", "", "Magia y fantasía", 3],
  ["cloak", "capa", "", "Magia y fantasía", 3],
  ["prophecy", "profecía", "", "Magia y fantasía", 3],
  ["realm", "reino", "", "Magia y fantasía", 3],
  ["spellbook", "libro de hechizos", "", "Magia y fantasía", 3],
  ["apprentice", "aprendiz", "", "Magia y fantasía", 3],
  ["amulet", "amuleto", "", "Magia y fantasía", 3],
  ["centaur", "centauro", "", "Magia y fantasía", 3],
  ["labyrinth", "laberinto", "", "Magia y fantasía", 3],

  // ---------- Palabras útiles ----------
  ["what", "qué", "", "Palabras útiles", 1],
  ["where", "dónde", "", "Palabras útiles", 1],
  ["who", "quién", "", "Palabras útiles", 1],
  ["when", "cuándo", "", "Palabras útiles", 1],
  ["why", "por qué", "", "Palabras útiles", 1],
  ["how", "cómo", "", "Palabras útiles", 1],
  ["and", "y", "", "Palabras útiles", 1],
  ["but", "pero", "", "Palabras útiles", 1],
  ["because", "porque", "", "Palabras útiles", 1],
  ["under", "debajo de", "", "Palabras útiles", 1],
  ["with", "con", "", "Palabras útiles", 1],
  ["which", "cuál", "", "Palabras útiles", 2],
  ["near", "cerca de", "", "Palabras útiles", 2],
  ["far", "lejos", "", "Palabras útiles", 2],
  ["behind", "detrás de", "", "Palabras útiles", 2],
  ["between", "entre", "", "Palabras útiles", 2],
  ["always", "siempre", "", "Palabras útiles", 2],
  ["never", "nunca", "", "Palabras útiles", 2],
  ["sometimes", "a veces", "", "Palabras útiles", 2],
  ["often", "a menudo", "", "Palabras útiles", 2],
  ["maybe", "quizás", "", "Palabras útiles", 2],
  ["also", "también", "", "Palabras útiles", 2],
  ["then", "luego", "", "Palabras útiles", 2],
  ["before", "antes", "", "Palabras útiles", 2],
  ["after", "después", "", "Palabras útiles", 2],
  ["inside", "adentro", "", "Palabras útiles", 2],
  ["outside", "afuera", "", "Palabras útiles", 2],
  ["above", "por encima de", "", "Palabras útiles", 2],
  ["although", "aunque", "", "Palabras útiles", 3],
  ["however", "sin embargo", "", "Palabras útiles", 3],
  ["therefore", "por lo tanto", "", "Palabras útiles", 3],
  ["meanwhile", "mientras tanto", "", "Palabras útiles", 3],
  ["whose", "de quién", "", "Palabras útiles", 3],
  ["unless", "a menos que", "", "Palabras útiles", 3],
  ["despite", "a pesar de", "", "Palabras útiles", 3],
  ["toward", "hacia", "", "Palabras útiles", 3],
  ["besides", "además", "", "Palabras útiles", 3],
  ["already", "ya", "", "Palabras útiles", 3],
  ["against", "contra", "", "Palabras útiles", 3],
  ["instead of", "en lugar de", "", "Palabras útiles", 3],
  ["suddenly", "de repente", "", "Palabras útiles", 3]
);
