/* Vocabulario de inglés — parte 1. Formato: [inglés, español, emoji o "", categoría, nivel 1-3] */
(window.INGLES = window.INGLES || { vocab: [], gramatica: [], frases: [] }).vocab.push(
  // ── Animales ──
  ["cat", "gato", "🐱", "Animales", 1],
  ["dog", "perro", "🐶", "Animales", 1],
  ["bird", "pájaro", "🐦", "Animales", 1],
  ["fish", "pez", "🐟", "Animales", 1],
  ["horse", "caballo", "🐴", "Animales", 1],
  ["cow", "vaca", "🐮", "Animales", 1],
  ["pig", "chancho (cerdo)", "🐷", "Animales", 1],
  ["duck", "pato", "🦆", "Animales", 1],
  ["mouse", "ratón", "🐭", "Animales", 1],
  ["rabbit", "conejo", "🐰", "Animales", 1],
  ["lion", "león", "🦁", "Animales", 1],
  ["giraffe", "jirafa", "🦒", "Animales", 2],
  ["elephant", "elefante", "🐘", "Animales", 2],
  ["monkey", "mono", "🐒", "Animales", 2],
  ["tiger", "tigre", "🐯", "Animales", 2],
  ["bear", "oso", "🐻", "Animales", 2],
  ["sheep", "oveja", "🐑", "Animales", 2],
  ["frog", "rana", "🐸", "Animales", 2],
  ["snake", "serpiente", "🐍", "Animales", 2],
  ["turtle", "tortuga", "🐢", "Animales", 2],
  ["penguin", "pingüino", "🐧", "Animales", 2],
  ["butterfly", "mariposa", "🦋", "Animales", 2],
  ["whale", "ballena", "🐋", "Animales", 2],
  ["owl", "búho", "🦉", "Animales", 2],
  ["fox", "zorro", "🦊", "Animales", 2],
  ["dolphin", "delfín", "🐬", "Animales", 2],
  ["bee", "abeja", "🐝", "Animales", 2],
  ["squirrel", "ardilla", "🐿️", "Animales", 3],
  ["hedgehog", "erizo", "🦔", "Animales", 3],
  ["octopus", "pulpo", "🐙", "Animales", 3],
  ["jellyfish", "medusa (aguaviva)", "", "Animales", 3],
  ["peacock", "pavo real", "🦚", "Animales", 3],
  ["flamingo", "flamenco", "🦩", "Animales", 3],
  ["hummingbird", "picaflor (colibrí)", "", "Animales", 3],
  ["beaver", "castor", "🦫", "Animales", 3],
  ["bat", "murciélago", "🦇", "Animales", 3],
  ["seal", "foca", "🦭", "Animales", 3],
  ["snail", "caracol", "🐌", "Animales", 3],

  // ── Comida ──
  ["apple", "manzana", "🍎", "Comida", 1],
  ["banana", "plátano", "🍌", "Comida", 1],
  ["bread", "pan", "🍞", "Comida", 1],
  ["milk", "leche", "🥛", "Comida", 1],
  ["egg", "huevo", "🥚", "Comida", 1],
  ["water", "agua", "💧", "Comida", 1],
  ["cheese", "queso", "🧀", "Comida", 1],
  ["cake", "torta (pastel)", "🍰", "Comida", 1],
  ["ice cream", "helado", "🍦", "Comida", 1],
  ["juice", "jugo", "🧃", "Comida", 1],
  ["strawberry", "frutilla (fresa)", "🍓", "Comida", 2],
  ["avocado", "palta (aguacate)", "🥑", "Comida", 2],
  ["grape", "uva", "🍇", "Comida", 2],
  ["watermelon", "sandía", "🍉", "Comida", 2],
  ["pineapple", "piña", "🍍", "Comida", 2],
  ["lemon", "limón", "🍋", "Comida", 2],
  ["cherry", "cereza", "🍒", "Comida", 2],
  ["carrot", "zanahoria", "🥕", "Comida", 2],
  ["potato", "papa (patata)", "🥔", "Comida", 2],
  ["tomato", "tomate", "🍅", "Comida", 2],
  ["corn", "choclo (maíz)", "🌽", "Comida", 2],
  ["cookie", "galleta", "🍪", "Comida", 2],
  ["rice", "arroz", "🍚", "Comida", 2],
  ["soup", "sopa", "", "Comida", 2],
  ["meat", "carne", "🥩", "Comida", 2],
  ["pear", "pera", "🍐", "Comida", 2],
  ["breakfast", "desayuno", "", "Comida", 2],
  ["lunch", "almuerzo", "", "Comida", 2],
  ["cauliflower", "coliflor", "", "Comida", 3],
  ["broccoli", "brócoli", "🥦", "Comida", 3],
  ["cucumber", "pepino", "🥒", "Comida", 3],
  ["garlic", "ajo", "🧄", "Comida", 3],
  ["onion", "cebolla", "🧅", "Comida", 3],
  ["eggplant", "berenjena", "🍆", "Comida", 3],
  ["pumpkin", "zapallo (calabaza)", "", "Comida", 3],
  ["flour", "harina", "", "Comida", 3],
  ["blueberry", "arándano", "🫐", "Comida", 3],
  ["spinach", "espinaca", "", "Comida", 3],
  ["raspberry", "frambuesa", "", "Comida", 3],
  ["honey", "miel", "🍯", "Comida", 3],

  // ── Cuerpo ──
  ["head", "cabeza", "", "Cuerpo", 1],
  ["eye", "ojo", "👁️", "Cuerpo", 1],
  ["nose", "nariz", "👃", "Cuerpo", 1],
  ["mouth", "boca", "👄", "Cuerpo", 1],
  ["ear", "oreja", "👂", "Cuerpo", 1],
  ["hand", "mano", "✋", "Cuerpo", 1],
  ["foot", "pie", "🦶", "Cuerpo", 1],
  ["arm", "brazo", "", "Cuerpo", 1],
  ["leg", "pierna", "🦵", "Cuerpo", 1],
  ["hair", "pelo (cabello)", "", "Cuerpo", 1],
  ["tooth", "diente", "🦷", "Cuerpo", 2],
  ["face", "cara", "", "Cuerpo", 2],
  ["finger", "dedo", "", "Cuerpo", 2],
  ["knee", "rodilla", "", "Cuerpo", 2],
  ["neck", "cuello", "", "Cuerpo", 2],
  ["shoulder", "hombro", "", "Cuerpo", 2],
  ["back", "espalda", "", "Cuerpo", 2],
  ["tongue", "lengua", "👅", "Cuerpo", 2],
  ["lip", "labio", "", "Cuerpo", 2],
  ["brain", "cerebro", "🧠", "Cuerpo", 2],
  ["bone", "hueso", "🦴", "Cuerpo", 2],
  ["stomach", "estómago", "", "Cuerpo", 2],
  ["cheek", "mejilla", "", "Cuerpo", 2],
  ["skin", "piel", "", "Cuerpo", 2],
  ["eyebrow", "ceja", "", "Cuerpo", 3],
  ["eyelash", "pestaña", "", "Cuerpo", 3],
  ["elbow", "codo", "", "Cuerpo", 3],
  ["ankle", "tobillo", "", "Cuerpo", 3],
  ["thumb", "pulgar", "", "Cuerpo", 3],
  ["toe", "dedo del pie", "", "Cuerpo", 3],
  ["forehead", "frente", "", "Cuerpo", 3],
  ["chin", "mentón (barbilla)", "", "Cuerpo", 3],
  ["lung", "pulmón", "🫁", "Cuerpo", 3],
  ["muscle", "músculo", "💪", "Cuerpo", 3],
  ["throat", "garganta", "", "Cuerpo", 3],
  ["fingernail", "uña", "", "Cuerpo", 3],

  // ── Ropa ──
  ["t-shirt", "polera (camiseta)", "👕", "Ropa", 1],
  ["shoe", "zapato", "👞", "Ropa", 1],
  ["hat", "sombrero", "", "Ropa", 1],
  ["dress", "vestido", "👗", "Ropa", 1],
  ["sock", "calcetín", "🧦", "Ropa", 1],
  ["pants", "pantalón", "👖", "Ropa", 1],
  ["coat", "abrigo", "🧥", "Ropa", 1],
  ["skirt", "falda", "", "Ropa", 1],
  ["sneakers", "zapatillas", "👟", "Ropa", 1],
  ["shirt", "camisa", "", "Ropa", 1],
  ["cap", "jockey (gorra)", "🧢", "Ropa", 2],
  ["boot", "bota", "👢", "Ropa", 2],
  ["glasses", "anteojos (lentes)", "👓", "Ropa", 2],
  ["scarf", "bufanda", "🧣", "Ropa", 2],
  ["glove", "guante", "🧤", "Ropa", 2],
  ["jacket", "chaqueta", "", "Ropa", 2],
  ["sweater", "chaleco (suéter)", "", "Ropa", 2],
  ["shorts", "shorts (pantalón corto)", "🩳", "Ropa", 2],
  ["pajamas", "pijama", "", "Ropa", 2],
  ["swimsuit", "traje de baño", "🩱", "Ropa", 2],
  ["belt", "cinturón", "", "Ropa", 2],
  ["button", "botón", "", "Ropa", 2],
  ["pocket", "bolsillo", "", "Ropa", 2],
  ["umbrella", "paraguas", "☂️", "Ropa", 2],
  ["crown", "corona", "👑", "Ropa", 2],
  ["ring", "anillo", "💍", "Ropa", 2],
  ["tie", "corbata", "👔", "Ropa", 2],
  ["sandal", "sandalia", "👡", "Ropa", 2],
  ["necklace", "collar", "", "Ropa", 3],
  ["bracelet", "pulsera", "", "Ropa", 3],
  ["earring", "aro (arete)", "", "Ropa", 3],
  ["zipper", "cierre (cremallera)", "", "Ropa", 3],
  ["sleeve", "manga", "", "Ropa", 3],
  ["hood", "capucha", "", "Ropa", 3],
  ["overalls", "jardinera (overol)", "", "Ropa", 3],
  ["raincoat", "impermeable", "", "Ropa", 3],
  ["handbag", "cartera", "👜", "Ropa", 3],
  ["costume", "disfraz", "", "Ropa", 3],
  ["apron", "delantal", "", "Ropa", 3],
  ["slippers", "pantuflas", "", "Ropa", 3],

  // ── Casa ──
  ["house", "casa", "🏠", "Casa", 1],
  ["door", "puerta", "🚪", "Casa", 1],
  ["window", "ventana", "🪟", "Casa", 1],
  ["bed", "cama", "🛏️", "Casa", 1],
  ["table", "mesa", "", "Casa", 1],
  ["chair", "silla", "🪑", "Casa", 1],
  ["kitchen", "cocina", "", "Casa", 1],
  ["bathroom", "baño", "", "Casa", 1],
  ["bedroom", "pieza (dormitorio)", "", "Casa", 1],
  ["television", "tele (televisor)", "📺", "Casa", 1],
  ["sofa", "sillón (sofá)", "🛋️", "Casa", 1],
  ["garden", "jardín", "", "Casa", 2],
  ["roof", "techo", "", "Casa", 2],
  ["wall", "pared", "", "Casa", 2],
  ["floor", "piso (suelo)", "", "Casa", 2],
  ["stairs", "escalera", "", "Casa", 2],
  ["key", "llave", "🔑", "Casa", 2],
  ["mirror", "espejo", "🪞", "Casa", 2],
  ["clock", "reloj", "", "Casa", 2],
  ["fridge", "refrigerador", "", "Casa", 2],
  ["oven", "horno", "", "Casa", 2],
  ["pillow", "almohada", "", "Casa", 2],
  ["blanket", "frazada (manta)", "", "Casa", 2],
  ["shower", "ducha", "🚿", "Casa", 2],
  ["soap", "jabón", "🧼", "Casa", 2],
  ["towel", "toalla", "", "Casa", 2],
  ["spoon", "cuchara", "🥄", "Casa", 2],
  ["knife", "cuchillo", "🔪", "Casa", 2],
  ["plate", "plato", "", "Casa", 2],
  ["toilet", "inodoro (WC)", "🚽", "Casa", 3],
  ["candle", "vela", "🕯️", "Casa", 3],
  ["broom", "escoba", "🧹", "Casa", 3],
  ["basket", "canasto", "🧺", "Casa", 3],
  ["attic", "entretecho (ático)", "", "Casa", 3],
  ["chimney", "chimenea", "", "Casa", 3],
  ["carpet", "alfombra", "", "Casa", 3],
  ["shelf", "repisa", "", "Casa", 3],
  ["drawer", "cajón", "", "Casa", 3],
  ["curtain", "cortina", "", "Casa", 3],
  ["doorbell", "timbre", "", "Casa", 3],
  ["washing machine", "lavadora", "", "Casa", 3],
  ["vacuum cleaner", "aspiradora", "", "Casa", 3],
  ["balcony", "balcón", "", "Casa", 3],
  ["hallway", "pasillo", "", "Casa", 3],

  // ── Colegio ──
  ["school", "colegio", "🏫", "Colegio", 1],
  ["book", "libro", "📖", "Colegio", 1],
  ["pencil", "lápiz", "✏️", "Colegio", 1],
  ["pen", "lápiz pasta (bolígrafo)", "🖊️", "Colegio", 1],
  ["teacher", "profesor", "", "Colegio", 1],
  ["backpack", "mochila", "🎒", "Colegio", 1],
  ["eraser", "goma (borrador)", "", "Colegio", 1],
  ["ruler", "regla", "📏", "Colegio", 1],
  ["scissors", "tijeras", "✂️", "Colegio", 1],
  ["notebook", "cuaderno", "📓", "Colegio", 1],
  ["classroom", "sala de clases", "", "Colegio", 2],
  ["desk", "pupitre", "", "Colegio", 2],
  ["glue", "pegamento", "", "Colegio", 2],
  ["paper", "papel", "", "Colegio", 2],
  ["board", "pizarra", "", "Colegio", 2],
  ["homework", "tarea", "", "Colegio", 2],
  ["test", "prueba", "", "Colegio", 2],
  ["library", "biblioteca", "", "Colegio", 2],
  ["map", "mapa", "🗺️", "Colegio", 2],
  ["math", "matemáticas", "", "Colegio", 2],
  ["science", "ciencias", "", "Colegio", 2],
  ["music", "música", "🎵", "Colegio", 2],
  ["art", "arte", "🎨", "Colegio", 2],
  ["student", "alumno (estudiante)", "", "Colegio", 2],
  ["crayon", "lápiz de cera", "🖍️", "Colegio", 2],
  ["computer", "computador (computadora)", "💻", "Colegio", 2],
  ["question", "pregunta", "❓", "Colegio", 2],
  ["answer", "respuesta", "", "Colegio", 2],
  ["dictionary", "diccionario", "", "Colegio", 3],
  ["principal", "director del colegio", "", "Colegio", 3],
  ["timetable", "horario", "", "Colegio", 3],
  ["pencil case", "estuche", "", "Colegio", 3],
  ["microscope", "microscopio", "🔬", "Colegio", 3],
  ["experiment", "experimento", "", "Colegio", 3],
  ["highlighter", "destacador", "", "Colegio", 3],
  ["stapler", "corchetera (engrapadora)", "", "Colegio", 3],
  ["pushpin", "chinche", "📌", "Colegio", 3],
  ["recess", "recreo", "", "Colegio", 3],
  ["sharpener", "sacapuntas", "", "Colegio", 3],
  ["geography", "geografía", "", "Colegio", 3],
  ["spelling", "ortografía", "", "Colegio", 3],

  // ── Familia y personas ──
  ["mom", "mamá", "", "Familia y personas", 1],
  ["dad", "papá", "", "Familia y personas", 1],
  ["brother", "hermano", "", "Familia y personas", 1],
  ["sister", "hermana", "", "Familia y personas", 1],
  ["baby", "bebé", "👶", "Familia y personas", 1],
  ["family", "familia", "", "Familia y personas", 1],
  ["grandmother", "abuela", "👵", "Familia y personas", 1],
  ["grandfather", "abuelo", "👴", "Familia y personas", 1],
  ["friend", "amigo", "", "Familia y personas", 1],
  ["boy", "niño", "👦", "Familia y personas", 1],
  ["girl", "niña", "👧", "Familia y personas", 1],
  ["man", "hombre", "👨", "Familia y personas", 2],
  ["woman", "mujer", "👩", "Familia y personas", 2],
  ["aunt", "tía", "", "Familia y personas", 2],
  ["uncle", "tío", "", "Familia y personas", 2],
  ["cousin", "primo", "", "Familia y personas", 2],
  ["son", "hijo", "", "Familia y personas", 2],
  ["daughter", "hija", "", "Familia y personas", 2],
  ["parents", "papás (padres)", "", "Familia y personas", 2],
  ["neighbor", "vecino", "", "Familia y personas", 2],
  ["doctor", "doctor (médico)", "", "Familia y personas", 2],
  ["nurse", "enfermero", "", "Familia y personas", 2],
  ["firefighter", "bombero", "", "Familia y personas", 2],
  ["police officer", "carabinero (policía)", "👮", "Familia y personas", 2],
  ["farmer", "granjero", "", "Familia y personas", 2],
  ["king", "rey", "", "Familia y personas", 2],
  ["queen", "reina", "", "Familia y personas", 2],
  ["prince", "príncipe", "🤴", "Familia y personas", 2],
  ["princess", "princesa", "👸", "Familia y personas", 2],
  ["nephew", "sobrino", "", "Familia y personas", 3],
  ["niece", "sobrina", "", "Familia y personas", 3],
  ["grandson", "nieto", "", "Familia y personas", 3],
  ["granddaughter", "nieta", "", "Familia y personas", 3],
  ["husband", "esposo", "", "Familia y personas", 3],
  ["wife", "esposa", "", "Familia y personas", 3],
  ["twin", "gemelo", "", "Familia y personas", 3],
  ["astronaut", "astronauta", "", "Familia y personas", 3],
  ["scientist", "científico", "", "Familia y personas", 3],
  ["veterinarian", "veterinario", "", "Familia y personas", 3],
  ["engineer", "ingeniero", "", "Familia y personas", 3],
  ["mail carrier", "cartero", "", "Familia y personas", 3],
  ["teenager", "adolescente", "", "Familia y personas", 3],
  ["godmother", "madrina", "", "Familia y personas", 3],

  // ── Colores y formas ──
  ["red", "rojo", "🔴", "Colores y formas", 1],
  ["blue", "azul", "🔵", "Colores y formas", 1],
  ["green", "verde", "🟢", "Colores y formas", 1],
  ["yellow", "amarillo", "🟡", "Colores y formas", 1],
  ["black", "negro", "⚫", "Colores y formas", 1],
  ["white", "blanco", "⚪", "Colores y formas", 1],
  ["orange", "naranjo (naranja)", "🟠", "Colores y formas", 1],
  ["pink", "rosado", "", "Colores y formas", 1],
  ["purple", "morado", "🟣", "Colores y formas", 1],
  ["brown", "café (marrón)", "🟤", "Colores y formas", 1],
  ["circle", "círculo", "", "Colores y formas", 1],
  ["star", "estrella", "⭐", "Colores y formas", 1],
  ["heart", "corazón", "❤️", "Colores y formas", 1],
  ["gray", "gris", "", "Colores y formas", 2],
  ["square", "cuadrado", "", "Colores y formas", 2],
  ["triangle", "triángulo", "", "Colores y formas", 2],
  ["rectangle", "rectángulo", "", "Colores y formas", 2],
  ["oval", "óvalo", "", "Colores y formas", 2],
  ["line", "línea", "", "Colores y formas", 2],
  ["dot", "punto", "", "Colores y formas", 2],
  ["cube", "cubo", "", "Colores y formas", 2],
  ["arrow", "flecha", "➡️", "Colores y formas", 2],
  ["light blue", "celeste", "", "Colores y formas", 2],
  ["golden", "dorado", "", "Colores y formas", 2],
  ["silver", "plateado", "", "Colores y formas", 2],
  ["shape", "forma", "", "Colores y formas", 2],
  ["dark", "oscuro", "", "Colores y formas", 2],
  ["navy blue", "azul marino", "", "Colores y formas", 3],
  ["turquoise", "turquesa", "", "Colores y formas", 3],
  ["violet", "violeta", "", "Colores y formas", 3],
  ["sphere", "esfera", "", "Colores y formas", 3],
  ["cylinder", "cilindro", "", "Colores y formas", 3],
  ["pyramid", "pirámide", "", "Colores y formas", 3],
  ["cone", "cono", "", "Colores y formas", 3],
  ["pentagon", "pentágono", "", "Colores y formas", 3],
  ["hexagon", "hexágono", "", "Colores y formas", 3],
  ["octagon", "octágono", "", "Colores y formas", 3],
  ["rhombus", "rombo", "", "Colores y formas", 3],
  ["spiral", "espiral", "", "Colores y formas", 3],
  ["stripe", "raya (franja)", "", "Colores y formas", 3],

  // ── Naturaleza y clima ──
  ["sun", "sol", "☀️", "Naturaleza y clima", 1],
  ["moon", "luna", "🌙", "Naturaleza y clima", 1],
  ["tree", "árbol", "🌳", "Naturaleza y clima", 1],
  ["flower", "flor", "🌸", "Naturaleza y clima", 1],
  ["rain", "lluvia", "🌧️", "Naturaleza y clima", 1],
  ["snow", "nieve", "❄️", "Naturaleza y clima", 1],
  ["sky", "cielo", "", "Naturaleza y clima", 1],
  ["cloud", "nube", "☁️", "Naturaleza y clima", 1],
  ["sea", "mar", "", "Naturaleza y clima", 1],
  ["fire", "fuego", "🔥", "Naturaleza y clima", 1],
  ["mountain", "montaña", "⛰️", "Naturaleza y clima", 2],
  ["river", "río", "", "Naturaleza y clima", 2],
  ["beach", "playa", "🏖️", "Naturaleza y clima", 2],
  ["grass", "pasto (hierba)", "", "Naturaleza y clima", 2],
  ["leaf", "hoja", "🍃", "Naturaleza y clima", 2],
  ["wind", "viento", "", "Naturaleza y clima", 2],
  ["rainbow", "arcoíris", "🌈", "Naturaleza y clima", 2],
  ["lake", "lago", "", "Naturaleza y clima", 2],
  ["forest", "bosque", "", "Naturaleza y clima", 2],
  ["island", "isla", "🏝️", "Naturaleza y clima", 2],
  ["volcano", "volcán", "🌋", "Naturaleza y clima", 2],
  ["desert", "desierto", "🏜️", "Naturaleza y clima", 2],
  ["rock", "roca", "🪨", "Naturaleza y clima", 2],
  ["sand", "arena", "", "Naturaleza y clima", 2],
  ["ice", "hielo", "🧊", "Naturaleza y clima", 2],
  ["planet", "planeta", "🪐", "Naturaleza y clima", 2],
  ["wave", "ola", "🌊", "Naturaleza y clima", 2],
  ["spring", "primavera", "", "Naturaleza y clima", 2],
  ["summer", "verano", "", "Naturaleza y clima", 2],
  ["autumn", "otoño", "🍂", "Naturaleza y clima", 2],
  ["winter", "invierno", "", "Naturaleza y clima", 2],
  ["thunderstorm", "tormenta eléctrica", "⛈️", "Naturaleza y clima", 3],
  ["lightning", "rayo (relámpago)", "⚡", "Naturaleza y clima", 3],
  ["thunder", "trueno", "", "Naturaleza y clima", 3],
  ["hail", "granizo", "", "Naturaleza y clima", 3],
  ["earthquake", "terremoto", "", "Naturaleza y clima", 3],
  ["waterfall", "cascada", "", "Naturaleza y clima", 3],
  ["valley", "valle", "", "Naturaleza y clima", 3],
  ["cliff", "acantilado", "", "Naturaleza y clima", 3],
  ["glacier", "glaciar", "", "Naturaleza y clima", 3],
  ["drizzle", "llovizna", "", "Naturaleza y clima", 3],
  ["puddle", "charco", "", "Naturaleza y clima", 3],
  ["fog", "niebla", "🌫️", "Naturaleza y clima", 3],
  ["cave", "cueva", "", "Naturaleza y clima", 3],
  ["seed", "semilla", "", "Naturaleza y clima", 3],
  ["root", "raíz", "", "Naturaleza y clima", 3],
  ["comet", "cometa", "☄️", "Naturaleza y clima", 3],

  // ── Transporte y lugares ──
  ["car", "auto", "🚗", "Transporte y lugares", 1],
  ["bus", "micro (bus)", "🚌", "Transporte y lugares", 1],
  ["train", "tren", "🚆", "Transporte y lugares", 1],
  ["airplane", "avión", "✈️", "Transporte y lugares", 1],
  ["bicycle", "bicicleta", "🚲", "Transporte y lugares", 1],
  ["boat", "bote", "", "Transporte y lugares", 1],
  ["city", "ciudad", "🏙️", "Transporte y lugares", 1],
  ["park", "parque", "", "Transporte y lugares", 1],
  ["street", "calle", "", "Transporte y lugares", 1],
  ["store", "tienda", "", "Transporte y lugares", 1],
  ["zoo", "zoológico", "", "Transporte y lugares", 1],
  ["truck", "camión", "🚚", "Transporte y lugares", 2],
  ["ship", "barco", "🚢", "Transporte y lugares", 2],
  ["helicopter", "helicóptero", "🚁", "Transporte y lugares", 2],
  ["motorcycle", "moto", "🏍️", "Transporte y lugares", 2],
  ["subway", "metro", "🚇", "Transporte y lugares", 2],
  ["rocket", "cohete", "🚀", "Transporte y lugares", 2],
  ["fire truck", "carro de bomberos", "🚒", "Transporte y lugares", 2],
  ["ambulance", "ambulancia", "🚑", "Transporte y lugares", 2],
  ["airport", "aeropuerto", "", "Transporte y lugares", 2],
  ["train station", "estación de tren", "🚉", "Transporte y lugares", 2],
  ["bridge", "puente", "", "Transporte y lugares", 2],
  ["museum", "museo", "", "Transporte y lugares", 2],
  ["restaurant", "restaurante", "", "Transporte y lugares", 2],
  ["supermarket", "supermercado", "", "Transporte y lugares", 2],
  ["farm", "granja", "", "Transporte y lugares", 2],
  ["castle", "castillo", "🏰", "Transporte y lugares", 2],
  ["church", "iglesia", "⛪", "Transporte y lugares", 2],
  ["hospital", "hospital", "🏥", "Transporte y lugares", 2],
  ["lighthouse", "faro", "", "Transporte y lugares", 3],
  ["traffic light", "semáforo", "🚦", "Transporte y lugares", 3],
  ["sidewalk", "vereda (acera)", "", "Transporte y lugares", 3],
  ["crosswalk", "paso de cebra", "", "Transporte y lugares", 3],
  ["tractor", "tractor", "🚜", "Transporte y lugares", 3],
  ["sailboat", "velero", "⛵", "Transporte y lugares", 3],
  ["submarine", "submarino", "", "Transporte y lugares", 3],
  ["hot air balloon", "globo aerostático", "", "Transporte y lugares", 3],
  ["skyscraper", "rascacielos", "", "Transporte y lugares", 3],
  ["tunnel", "túnel", "", "Transporte y lugares", 3],
  ["harbor", "puerto", "", "Transporte y lugares", 3],
  ["neighborhood", "barrio", "", "Transporte y lugares", 3],
  ["pharmacy", "farmacia", "", "Transporte y lugares", 3],
  ["bakery", "panadería", "", "Transporte y lugares", 3],
  ["gas station", "bencinera (gasolinera)", "⛽", "Transporte y lugares", 3],
  ["cable car", "teleférico", "🚡", "Transporte y lugares", 3],
  ["highway", "autopista", "", "Transporte y lugares", 3]
);
